Running the test reports that the function `GetResultFromService()` returned a non-nil error,
but the implementation of the `error`-interface of type `ServiceError` then reports that it
is nil. What's going on?
